name: Run Fintech Founder Crawler

on:
  schedule:
    - cron: '0 9 * * 1'
  workflow_dispatch:

jobs:
  run-crawler:
    runs-on: ubuntu-latest
    
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v4

      - name: Setup Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.10'

      - name: Install Dependencies
        run: |
          pip install -r requirements.txt

      - name: Run Crawler Script
        env:
          PYTHONUNBUFFERED: "1"
          GCP_CREDENTIALS: ${{ secrets.GCP_CREDENTIALS }}
        run: python -u crawler.py
